### ISSUE TITLE
Add field for extra shares returned with FPMM liquidity actions

### ISSUE THREAD

**Issue by cag** [protofire/omen-subgraph#111]
Is this possible?

**Comment by KadenZipfel** [comment]
Since we don't have access to the probability of the outcome being purchased, I don't think we can determine how many extra shares are obtained, but I do think we could return the cost in collateral of the outcome shares and we could then check the historical probability to determine the amount of extra shares obtained from the front-end. I've briefly outlined how I think we can return the cost of the extra shares here: https://github.com/protofire/omen-subgraph/issues/118

**Comment by KadenZipfel** [comment]
Closing as https://github.com/protofire/omen-subgraph/issues/118 actually does return additional shares.
