### ISSUE TITLE
Withdraw sometimes returns zero for ColalteralTokenAmount

### ISSUE THREAD

**Issue by Mi-Lan** [protofire/omen-subgraph#121]
- Here is example of one id where collateralTokenAmount is zero:
- "0xb4277c368b817db02bab8b684c9bfe10200461f70x9671dc03ec719ff66c561e2dc73411b041548b730x12"
![Screenshot 2021-01-15 at 22 17 22](https://user-images.githubusercontent.com/33226956/104779478-788e8000-577f-11eb-88d3-93f3d9f0cb5a.png)

**Comment by Mi-Lan** [comment]
- here is one transaction that is showing collateralToken amount zero but on contract side it actually displays 9.28 amount as it should  
- https://rinkeby.etherscan.io/tx/0x3a56a3af0e1616b4c994f56434895f0143b6233ea0185a489465f1739578a812
- screenshot..... also there is this error don't know if it's related somehow?
![Screenshot 2021-01-18 at 21 31 02](https://user-images.githubusercontent.com/33226956/104960426-7a04b600-59d4-11eb-8cde-810f3e7bbab6.png)

**Comment by Mi-Lan** [comment]
- With continued investigation into the issue 
 https://tenor.com/view/columbo-detective-confused-thinking-peter-falk-gif-13175857

**Comment by KadenZipfel** [comment]
@Mi-Lan So it looks like the first transfer in 2. was removing funds from the fee pool, as seen [here](https://github.com/protofire/omen-subgraph/blob/712f4eb535ec8a948fe31b6c072b5950432a6f4e/src/FixedProductMarketMakerMapping.ts#L135), so 1. must have not had any earned fees, which makes sense. But of course the fees earned is not the value we're looking for. Of course that first transfer value is the same value used for `collateralTokenAmount`, but I'm not sure why or even what the original intention of `collateralTokenAmount` was. 

For `fpmmLiquidity.collateralTokenAmount` on the other hand, we are using `min(outcomeTokenAmounts)`, which makes sense since the lower value of our `outcomeTokenAmounts` would indicate to us the amount that was not removed, i.e. used to purchase outcome shares to keep the market probability consistent. This would then work similarly to adding funding events as it uses `max(outcomeTokenAmounts`, probably making it easier to include in your calculations.

I'm not sure why `fpmmTransaction.collateralTokenAmount` uses the amount of fees removed for liquidity removal though as it's inconsistent with what's done for adding liquidity, in fact it was previously consistent, it used to take the value of `fpmmLiquidity.collateralTokenAmount`.

What I would do here is:
- Figure out why `fpmmTransaction.collateralTokenAmount` was changed for liquidity removal
  - Maybe by looking through commit history
  - Either replace, leave as is, or create a new variable for this value (idk what should be done)
- Do the calculation for the additional shares amount within the subgraph and assign to a new variable
  - Should be the following for adding and removing liquidity: `max(outcomeTokenAmounts).minus(min(outcomeTokenAmounts)`
  - I'm not sure whether this would return the value in shares or collateral though, so might need to use the amount of shares to figure that out.
